! This automatically generated Fortran wrapper file allows codes
! written in Fortran to be called directly from C and translates all
! C-style arguments into expected Fortran-style arguments (with
! assumed size, local type declarations, etc.).


MODULE C_FLUX_MODULE
  IMPLICIT NONE


CONTAINS


  ! Getter and setter for DP.
  SUBROUTINE FLUX_MODULE_GET_DP(DP_LOCAL) BIND(C)
    USE FLUX_MODULE, ONLY: DP
    INTEGER :: DP_LOCAL
    DP_LOCAL = DP
  END SUBROUTINE FLUX_MODULE_GET_DP

  ! Getter and setter for IMAX.
  SUBROUTINE FLUX_MODULE_GET_IMAX(IMAX_LOCAL) BIND(C)
    USE FLUX_MODULE, ONLY: IMAX
    INTEGER :: IMAX_LOCAL
    IMAX_LOCAL = IMAX
  END SUBROUTINE FLUX_MODULE_GET_IMAX

  ! Getter and setter for JMAX.
  SUBROUTINE FLUX_MODULE_GET_JMAX(JMAX_LOCAL) BIND(C)
    USE FLUX_MODULE, ONLY: JMAX
    INTEGER :: JMAX_LOCAL
    JMAX_LOCAL = JMAX
  END SUBROUTINE FLUX_MODULE_GET_JMAX

  ! Getter and setter for ZERO.
  SUBROUTINE FLUX_MODULE_GET_ZERO(ZERO_LOCAL) BIND(C)
    USE FLUX_MODULE, ONLY: ZERO
    INTEGER :: ZERO_LOCAL
    ZERO_LOCAL = ZERO
  END SUBROUTINE FLUX_MODULE_GET_ZERO

  ! Getter and setter for F_XSI.
  SUBROUTINE FLUX_MODULE_GET_F_XSI(F_XSI_DIM_1, F_XSI_DIM_2, F_XSI_DIM_3, F_XSI_LOCAL) BIND(C)
    USE ISO_FORTRAN_ENV, ONLY: INT64
    USE FLUX_MODULE, ONLY: F_XSI
    INTEGER(KIND=INT64), INTENT(OUT) :: F_XSI_DIM_1
    INTEGER(KIND=INT64), INTENT(OUT) :: F_XSI_DIM_2
    INTEGER(KIND=INT64), INTENT(OUT) :: F_XSI_DIM_3
    INTEGER(KIND=INT64) :: F_XSI_LOCAL
    F_XSI_DIM_1 = SIZE(F_XSI, 1, KIND=INT64)
    F_XSI_DIM_2 = SIZE(F_XSI, 2, KIND=INT64)
    F_XSI_DIM_3 = SIZE(F_XSI, 3, KIND=INT64)
    F_XSI_LOCAL = LOC(F_XSI(1,1,1))
  END SUBROUTINE FLUX_MODULE_GET_F_XSI
  SUBROUTINE FLUX_MODULE_SET_F_XSI(F_XSI_DIM_1, F_XSI_DIM_2, F_XSI_DIM_3, F_XSI_LOCAL) BIND(C)
    USE FLUX_MODULE, ONLY: F_XSI
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: F_XSI_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: F_XSI_DIM_2
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: F_XSI_DIM_3
    REAL(KIND=DP), DIMENSION(F_XSI_DIM_1,F_XSI_DIM_2,F_XSI_DIM_3) :: F_XSI_LOCAL
    F_XSI = F_XSI_LOCAL
  END SUBROUTINE FLUX_MODULE_SET_F_XSI

  ! Getter and setter for F_ETA.
  SUBROUTINE FLUX_MODULE_GET_F_ETA(F_ETA_DIM_1, F_ETA_DIM_2, F_ETA_DIM_3, F_ETA_LOCAL) BIND(C)
    USE ISO_FORTRAN_ENV, ONLY: INT64
    USE FLUX_MODULE, ONLY: F_ETA
    INTEGER(KIND=INT64), INTENT(OUT) :: F_ETA_DIM_1
    INTEGER(KIND=INT64), INTENT(OUT) :: F_ETA_DIM_2
    INTEGER(KIND=INT64), INTENT(OUT) :: F_ETA_DIM_3
    INTEGER(KIND=INT64) :: F_ETA_LOCAL
    F_ETA_DIM_1 = SIZE(F_ETA, 1, KIND=INT64)
    F_ETA_DIM_2 = SIZE(F_ETA, 2, KIND=INT64)
    F_ETA_DIM_3 = SIZE(F_ETA, 3, KIND=INT64)
    F_ETA_LOCAL = LOC(F_ETA(1,1,1))
  END SUBROUTINE FLUX_MODULE_GET_F_ETA
  SUBROUTINE FLUX_MODULE_SET_F_ETA(F_ETA_DIM_1, F_ETA_DIM_2, F_ETA_DIM_3, F_ETA_LOCAL) BIND(C)
    USE FLUX_MODULE, ONLY: F_ETA
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: F_ETA_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: F_ETA_DIM_2
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: F_ETA_DIM_3
    REAL(KIND=DP), DIMENSION(F_ETA_DIM_1,F_ETA_DIM_2,F_ETA_DIM_3) :: F_ETA_LOCAL
    F_ETA = F_ETA_LOCAL
  END SUBROUTINE FLUX_MODULE_SET_F_ETA

  ! Getter and setter for VANLEER.
  SUBROUTINE FLUX_MODULE_GET_VANLEER(VANLEER_LOCAL) BIND(C)
    USE FLUX_MODULE, ONLY: VANLEER
    LOGICAL :: VANLEER_LOCAL
    VANLEER_LOCAL = VANLEER
  END SUBROUTINE FLUX_MODULE_GET_VANLEER
  SUBROUTINE FLUX_MODULE_SET_VANLEER(VANLEER_LOCAL) BIND(C)
    USE FLUX_MODULE, ONLY: VANLEER
    LOGICAL :: VANLEER_LOCAL
    VANLEER = VANLEER_LOCAL
  END SUBROUTINE FLUX_MODULE_SET_VANLEER

  ! Getter and setter for EPSILON.
  SUBROUTINE FLUX_MODULE_GET_EPSILON(EPSILON_LOCAL) BIND(C)
    USE FLUX_MODULE, ONLY: EPSILON
    REAL(KIND=DP) :: EPSILON_LOCAL
    EPSILON_LOCAL = EPSILON
  END SUBROUTINE FLUX_MODULE_GET_EPSILON

  ! Getter and setter for CONV.
  SUBROUTINE FLUX_MODULE_GET_CONV(CONV_LOCAL) BIND(C)
    USE FLUX_MODULE, ONLY: CONV
    REAL(KIND=DP) :: CONV_LOCAL
    CONV_LOCAL = CONV
  END SUBROUTINE FLUX_MODULE_GET_CONV
  SUBROUTINE FLUX_MODULE_SET_CONV(CONV_LOCAL) BIND(C)
    USE FLUX_MODULE, ONLY: CONV
    REAL(KIND=DP) :: CONV_LOCAL
    CONV = CONV_LOCAL
  END SUBROUTINE FLUX_MODULE_SET_CONV

  ! Getter and setter for CLIP_COUNT_RHO.
  SUBROUTINE FLUX_MODULE_GET_CLIP_COUNT_RHO(CLIP_COUNT_RHO_LOCAL) BIND(C)
    USE FLUX_MODULE, ONLY: CLIP_COUNT_RHO
    INTEGER :: CLIP_COUNT_RHO_LOCAL
    CLIP_COUNT_RHO_LOCAL = CLIP_COUNT_RHO
  END SUBROUTINE FLUX_MODULE_GET_CLIP_COUNT_RHO
  SUBROUTINE FLUX_MODULE_SET_CLIP_COUNT_RHO(CLIP_COUNT_RHO_LOCAL) BIND(C)
    USE FLUX_MODULE, ONLY: CLIP_COUNT_RHO
    INTEGER :: CLIP_COUNT_RHO_LOCAL
    CLIP_COUNT_RHO = CLIP_COUNT_RHO_LOCAL
  END SUBROUTINE FLUX_MODULE_SET_CLIP_COUNT_RHO

  ! Getter and setter for CLIP_COUNT_P.
  SUBROUTINE FLUX_MODULE_GET_CLIP_COUNT_P(CLIP_COUNT_P_LOCAL) BIND(C)
    USE FLUX_MODULE, ONLY: CLIP_COUNT_P
    INTEGER :: CLIP_COUNT_P_LOCAL
    CLIP_COUNT_P_LOCAL = CLIP_COUNT_P
  END SUBROUTINE FLUX_MODULE_GET_CLIP_COUNT_P
  SUBROUTINE FLUX_MODULE_SET_CLIP_COUNT_P(CLIP_COUNT_P_LOCAL) BIND(C)
    USE FLUX_MODULE, ONLY: CLIP_COUNT_P
    INTEGER :: CLIP_COUNT_P_LOCAL
    CLIP_COUNT_P = CLIP_COUNT_P_LOCAL
  END SUBROUTINE FLUX_MODULE_SET_CLIP_COUNT_P

  ! Getter and setter for TOTAL_FLUX_CALLS.
  SUBROUTINE FLUX_MODULE_GET_TOTAL_FLUX_CALLS(TOTAL_FLUX_CALLS_LOCAL) BIND(C)
    USE FLUX_MODULE, ONLY: TOTAL_FLUX_CALLS
    INTEGER :: TOTAL_FLUX_CALLS_LOCAL
    TOTAL_FLUX_CALLS_LOCAL = TOTAL_FLUX_CALLS
  END SUBROUTINE FLUX_MODULE_GET_TOTAL_FLUX_CALLS
  SUBROUTINE FLUX_MODULE_SET_TOTAL_FLUX_CALLS(TOTAL_FLUX_CALLS_LOCAL) BIND(C)
    USE FLUX_MODULE, ONLY: TOTAL_FLUX_CALLS
    INTEGER :: TOTAL_FLUX_CALLS_LOCAL
    TOTAL_FLUX_CALLS = TOTAL_FLUX_CALLS_LOCAL
  END SUBROUTINE FLUX_MODULE_SET_TOTAL_FLUX_CALLS

  ! Getter and setter for FREEZE_LIMITERS.
  SUBROUTINE FLUX_MODULE_GET_FREEZE_LIMITERS(FREEZE_LIMITERS_LOCAL) BIND(C)
    USE FLUX_MODULE, ONLY: FREEZE_LIMITERS
    LOGICAL :: FREEZE_LIMITERS_LOCAL
    FREEZE_LIMITERS_LOCAL = FREEZE_LIMITERS
  END SUBROUTINE FLUX_MODULE_GET_FREEZE_LIMITERS
  SUBROUTINE FLUX_MODULE_SET_FREEZE_LIMITERS(FREEZE_LIMITERS_LOCAL) BIND(C)
    USE FLUX_MODULE, ONLY: FREEZE_LIMITERS
    LOGICAL :: FREEZE_LIMITERS_LOCAL
    FREEZE_LIMITERS = FREEZE_LIMITERS_LOCAL
  END SUBROUTINE FLUX_MODULE_SET_FREEZE_LIMITERS

  ! Getter and setter for PSI_P_XSI_FROZEN.
  SUBROUTINE FLUX_MODULE_GET_PSI_P_XSI_FROZEN(PSI_P_XSI_FROZEN_DIM_1, PSI_P_XSI_FROZEN_DIM_2, PSI_P_XSI_FROZEN_DIM_3, PSI_P_XSI_FRO&
&ZEN_LOCAL) BIND(C)
    USE ISO_FORTRAN_ENV, ONLY: INT64
    USE FLUX_MODULE, ONLY: PSI_P_XSI_FROZEN
    INTEGER(KIND=INT64), INTENT(OUT) :: PSI_P_XSI_FROZEN_DIM_1
    INTEGER(KIND=INT64), INTENT(OUT) :: PSI_P_XSI_FROZEN_DIM_2
    INTEGER(KIND=INT64), INTENT(OUT) :: PSI_P_XSI_FROZEN_DIM_3
    INTEGER(KIND=INT64) :: PSI_P_XSI_FROZEN_LOCAL
    PSI_P_XSI_FROZEN_DIM_1 = SIZE(PSI_P_XSI_FROZEN, 1, KIND=INT64)
    PSI_P_XSI_FROZEN_DIM_2 = SIZE(PSI_P_XSI_FROZEN, 2, KIND=INT64)
    PSI_P_XSI_FROZEN_DIM_3 = SIZE(PSI_P_XSI_FROZEN, 3, KIND=INT64)
    PSI_P_XSI_FROZEN_LOCAL = LOC(PSI_P_XSI_FROZEN(1,1,1))
  END SUBROUTINE FLUX_MODULE_GET_PSI_P_XSI_FROZEN
  SUBROUTINE FLUX_MODULE_SET_PSI_P_XSI_FROZEN(PSI_P_XSI_FROZEN_DIM_1, PSI_P_XSI_FROZEN_DIM_2, PSI_P_XSI_FROZEN_DIM_3, PSI_P_XSI_FRO&
&ZEN_LOCAL) BIND(C)
    USE FLUX_MODULE, ONLY: PSI_P_XSI_FROZEN
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: PSI_P_XSI_FROZEN_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: PSI_P_XSI_FROZEN_DIM_2
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: PSI_P_XSI_FROZEN_DIM_3
    REAL(KIND=DP), DIMENSION(PSI_P_XSI_FROZEN_DIM_1,PSI_P_XSI_FROZEN_DIM_2,PSI_P_XSI_FROZEN_DIM_3) :: PSI_P_XSI_FROZEN_LOCAL
    PSI_P_XSI_FROZEN = PSI_P_XSI_FROZEN_LOCAL
  END SUBROUTINE FLUX_MODULE_SET_PSI_P_XSI_FROZEN

  ! Getter and setter for PSI_M_XSI_FROZEN.
  SUBROUTINE FLUX_MODULE_GET_PSI_M_XSI_FROZEN(PSI_M_XSI_FROZEN_DIM_1, PSI_M_XSI_FROZEN_DIM_2, PSI_M_XSI_FROZEN_DIM_3, PSI_M_XSI_FRO&
&ZEN_LOCAL) BIND(C)
    USE ISO_FORTRAN_ENV, ONLY: INT64
    USE FLUX_MODULE, ONLY: PSI_M_XSI_FROZEN
    INTEGER(KIND=INT64), INTENT(OUT) :: PSI_M_XSI_FROZEN_DIM_1
    INTEGER(KIND=INT64), INTENT(OUT) :: PSI_M_XSI_FROZEN_DIM_2
    INTEGER(KIND=INT64), INTENT(OUT) :: PSI_M_XSI_FROZEN_DIM_3
    INTEGER(KIND=INT64) :: PSI_M_XSI_FROZEN_LOCAL
    PSI_M_XSI_FROZEN_DIM_1 = SIZE(PSI_M_XSI_FROZEN, 1, KIND=INT64)
    PSI_M_XSI_FROZEN_DIM_2 = SIZE(PSI_M_XSI_FROZEN, 2, KIND=INT64)
    PSI_M_XSI_FROZEN_DIM_3 = SIZE(PSI_M_XSI_FROZEN, 3, KIND=INT64)
    PSI_M_XSI_FROZEN_LOCAL = LOC(PSI_M_XSI_FROZEN(1,1,1))
  END SUBROUTINE FLUX_MODULE_GET_PSI_M_XSI_FROZEN
  SUBROUTINE FLUX_MODULE_SET_PSI_M_XSI_FROZEN(PSI_M_XSI_FROZEN_DIM_1, PSI_M_XSI_FROZEN_DIM_2, PSI_M_XSI_FROZEN_DIM_3, PSI_M_XSI_FRO&
&ZEN_LOCAL) BIND(C)
    USE FLUX_MODULE, ONLY: PSI_M_XSI_FROZEN
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: PSI_M_XSI_FROZEN_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: PSI_M_XSI_FROZEN_DIM_2
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: PSI_M_XSI_FROZEN_DIM_3
    REAL(KIND=DP), DIMENSION(PSI_M_XSI_FROZEN_DIM_1,PSI_M_XSI_FROZEN_DIM_2,PSI_M_XSI_FROZEN_DIM_3) :: PSI_M_XSI_FROZEN_LOCAL
    PSI_M_XSI_FROZEN = PSI_M_XSI_FROZEN_LOCAL
  END SUBROUTINE FLUX_MODULE_SET_PSI_M_XSI_FROZEN

  ! Getter and setter for PSI_P_ETA_FROZEN.
  SUBROUTINE FLUX_MODULE_GET_PSI_P_ETA_FROZEN(PSI_P_ETA_FROZEN_DIM_1, PSI_P_ETA_FROZEN_DIM_2, PSI_P_ETA_FROZEN_DIM_3, PSI_P_ETA_FRO&
&ZEN_LOCAL) BIND(C)
    USE ISO_FORTRAN_ENV, ONLY: INT64
    USE FLUX_MODULE, ONLY: PSI_P_ETA_FROZEN
    INTEGER(KIND=INT64), INTENT(OUT) :: PSI_P_ETA_FROZEN_DIM_1
    INTEGER(KIND=INT64), INTENT(OUT) :: PSI_P_ETA_FROZEN_DIM_2
    INTEGER(KIND=INT64), INTENT(OUT) :: PSI_P_ETA_FROZEN_DIM_3
    INTEGER(KIND=INT64) :: PSI_P_ETA_FROZEN_LOCAL
    PSI_P_ETA_FROZEN_DIM_1 = SIZE(PSI_P_ETA_FROZEN, 1, KIND=INT64)
    PSI_P_ETA_FROZEN_DIM_2 = SIZE(PSI_P_ETA_FROZEN, 2, KIND=INT64)
    PSI_P_ETA_FROZEN_DIM_3 = SIZE(PSI_P_ETA_FROZEN, 3, KIND=INT64)
    PSI_P_ETA_FROZEN_LOCAL = LOC(PSI_P_ETA_FROZEN(1,1,1))
  END SUBROUTINE FLUX_MODULE_GET_PSI_P_ETA_FROZEN
  SUBROUTINE FLUX_MODULE_SET_PSI_P_ETA_FROZEN(PSI_P_ETA_FROZEN_DIM_1, PSI_P_ETA_FROZEN_DIM_2, PSI_P_ETA_FROZEN_DIM_3, PSI_P_ETA_FRO&
&ZEN_LOCAL) BIND(C)
    USE FLUX_MODULE, ONLY: PSI_P_ETA_FROZEN
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: PSI_P_ETA_FROZEN_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: PSI_P_ETA_FROZEN_DIM_2
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: PSI_P_ETA_FROZEN_DIM_3
    REAL(KIND=DP), DIMENSION(PSI_P_ETA_FROZEN_DIM_1,PSI_P_ETA_FROZEN_DIM_2,PSI_P_ETA_FROZEN_DIM_3) :: PSI_P_ETA_FROZEN_LOCAL
    PSI_P_ETA_FROZEN = PSI_P_ETA_FROZEN_LOCAL
  END SUBROUTINE FLUX_MODULE_SET_PSI_P_ETA_FROZEN

  ! Getter and setter for PSI_M_ETA_FROZEN.
  SUBROUTINE FLUX_MODULE_GET_PSI_M_ETA_FROZEN(PSI_M_ETA_FROZEN_DIM_1, PSI_M_ETA_FROZEN_DIM_2, PSI_M_ETA_FROZEN_DIM_3, PSI_M_ETA_FRO&
&ZEN_LOCAL) BIND(C)
    USE ISO_FORTRAN_ENV, ONLY: INT64
    USE FLUX_MODULE, ONLY: PSI_M_ETA_FROZEN
    INTEGER(KIND=INT64), INTENT(OUT) :: PSI_M_ETA_FROZEN_DIM_1
    INTEGER(KIND=INT64), INTENT(OUT) :: PSI_M_ETA_FROZEN_DIM_2
    INTEGER(KIND=INT64), INTENT(OUT) :: PSI_M_ETA_FROZEN_DIM_3
    INTEGER(KIND=INT64) :: PSI_M_ETA_FROZEN_LOCAL
    PSI_M_ETA_FROZEN_DIM_1 = SIZE(PSI_M_ETA_FROZEN, 1, KIND=INT64)
    PSI_M_ETA_FROZEN_DIM_2 = SIZE(PSI_M_ETA_FROZEN, 2, KIND=INT64)
    PSI_M_ETA_FROZEN_DIM_3 = SIZE(PSI_M_ETA_FROZEN, 3, KIND=INT64)
    PSI_M_ETA_FROZEN_LOCAL = LOC(PSI_M_ETA_FROZEN(1,1,1))
  END SUBROUTINE FLUX_MODULE_GET_PSI_M_ETA_FROZEN
  SUBROUTINE FLUX_MODULE_SET_PSI_M_ETA_FROZEN(PSI_M_ETA_FROZEN_DIM_1, PSI_M_ETA_FROZEN_DIM_2, PSI_M_ETA_FROZEN_DIM_3, PSI_M_ETA_FRO&
&ZEN_LOCAL) BIND(C)
    USE FLUX_MODULE, ONLY: PSI_M_ETA_FROZEN
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: PSI_M_ETA_FROZEN_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: PSI_M_ETA_FROZEN_DIM_2
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: PSI_M_ETA_FROZEN_DIM_3
    REAL(KIND=DP), DIMENSION(PSI_M_ETA_FROZEN_DIM_1,PSI_M_ETA_FROZEN_DIM_2,PSI_M_ETA_FROZEN_DIM_3) :: PSI_M_ETA_FROZEN_LOCAL
    PSI_M_ETA_FROZEN = PSI_M_ETA_FROZEN_LOCAL
  END SUBROUTINE FLUX_MODULE_SET_PSI_M_ETA_FROZEN

  ! Getter and setter for FREEZE_TOL.
  SUBROUTINE FLUX_MODULE_GET_FREEZE_TOL(FREEZE_TOL_LOCAL) BIND(C)
    USE FLUX_MODULE, ONLY: FREEZE_TOL
    REAL(KIND=DP) :: FREEZE_TOL_LOCAL
    FREEZE_TOL_LOCAL = FREEZE_TOL
  END SUBROUTINE FLUX_MODULE_GET_FREEZE_TOL

  ! Getter and setter for ONE.
  SUBROUTINE FLUX_MODULE_GET_ONE(ONE_LOCAL) BIND(C)
    USE FLUX_MODULE, ONLY: ONE
    REAL(KIND=DP) :: ONE_LOCAL
    ONE_LOCAL = ONE
  END SUBROUTINE FLUX_MODULE_GET_ONE

  ! Getter and setter for TWO.
  SUBROUTINE FLUX_MODULE_GET_TWO(TWO_LOCAL) BIND(C)
    USE FLUX_MODULE, ONLY: TWO
    REAL(KIND=DP) :: TWO_LOCAL
    TWO_LOCAL = TWO
  END SUBROUTINE FLUX_MODULE_GET_TWO

  ! Getter and setter for QUARTER.
  SUBROUTINE FLUX_MODULE_GET_QUARTER(QUARTER_LOCAL) BIND(C)
    USE FLUX_MODULE, ONLY: QUARTER
    REAL(KIND=DP) :: QUARTER_LOCAL
    QUARTER_LOCAL = QUARTER
  END SUBROUTINE FLUX_MODULE_GET_QUARTER

  ! Getter and setter for HALF.
  SUBROUTINE FLUX_MODULE_GET_HALF(HALF_LOCAL) BIND(C)
    USE FLUX_MODULE, ONLY: HALF
    REAL(KIND=DP) :: HALF_LOCAL
    HALF_LOCAL = HALF
  END SUBROUTINE FLUX_MODULE_GET_HALF

  ! Getter and setter for GAMMA.
  SUBROUTINE FLUX_MODULE_GET_GAMMA(GAMMA_LOCAL) BIND(C)
    USE FLUX_MODULE, ONLY: GAMMA
    REAL(KIND=DP) :: GAMMA_LOCAL
    GAMMA_LOCAL = GAMMA
  END SUBROUTINE FLUX_MODULE_GET_GAMMA

  ! Getter and setter for FOUR.
  SUBROUTINE FLUX_MODULE_GET_FOUR(FOUR_LOCAL) BIND(C)
    USE FLUX_MODULE, ONLY: FOUR
    REAL(KIND=DP) :: FOUR_LOCAL
    FOUR_LOCAL = FOUR
  END SUBROUTINE FLUX_MODULE_GET_FOUR

  
  SUBROUTINE C_COMPUTE_LIMITER_XSI(V_DIM_1, V_DIM_2, V_DIM_3, V, PSI_P_XSI_DIM_1, PSI_P_XSI_DIM_2, PSI_P_XSI_DIM_3, PSI_P_XSI, PSI_&
&M_XSI_DIM_1, PSI_M_XSI_DIM_2, PSI_M_XSI_DIM_3, PSI_M_XSI) BIND(C)
    USE ISO_C_BINDING, ONLY: C_BOOL
    USE FLUX_MODULE, ONLY: COMPUTE_LIMITER_XSI
    IMPLICIT NONE
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: V_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: V_DIM_2
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: V_DIM_3
    REAL(KIND=DP), INTENT(IN), DIMENSION(V_DIM_1,V_DIM_2,V_DIM_3) :: V
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: PSI_P_XSI_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: PSI_P_XSI_DIM_2
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: PSI_P_XSI_DIM_3
    REAL(KIND=DP), INTENT(OUT), DIMENSION(PSI_P_XSI_DIM_1,PSI_P_XSI_DIM_2,PSI_P_XSI_DIM_3) :: PSI_P_XSI
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: PSI_M_XSI_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: PSI_M_XSI_DIM_2
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: PSI_M_XSI_DIM_3
    REAL(KIND=DP), INTENT(OUT), DIMENSION(PSI_M_XSI_DIM_1,PSI_M_XSI_DIM_2,PSI_M_XSI_DIM_3) :: PSI_M_XSI
  
    CALL COMPUTE_LIMITER_XSI(V, PSI_P_XSI, PSI_M_XSI)
  END SUBROUTINE C_COMPUTE_LIMITER_XSI
  

  
  SUBROUTINE C_COMPUTE_L_R_STATES_XSI(V_DIM_1, V_DIM_2, V_DIM_3, V, VL_XSI_DIM_1, VL_XSI_DIM_2, VL_XSI_DIM_3, VL_XSI, VR_XSI_DIM_1,&
& VR_XSI_DIM_2, VR_XSI_DIM_3, VR_XSI) BIND(C)
    USE ISO_C_BINDING, ONLY: C_BOOL
    USE FLUX_MODULE, ONLY: COMPUTE_L_R_STATES_XSI
    IMPLICIT NONE
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: V_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: V_DIM_2
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: V_DIM_3
    REAL(KIND=DP), INTENT(IN), DIMENSION(V_DIM_1,V_DIM_2,V_DIM_3) :: V
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: VL_XSI_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: VL_XSI_DIM_2
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: VL_XSI_DIM_3
    REAL(KIND=DP), INTENT(OUT), DIMENSION(VL_XSI_DIM_1,VL_XSI_DIM_2,VL_XSI_DIM_3) :: VL_XSI
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: VR_XSI_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: VR_XSI_DIM_2
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: VR_XSI_DIM_3
    REAL(KIND=DP), INTENT(OUT), DIMENSION(VR_XSI_DIM_1,VR_XSI_DIM_2,VR_XSI_DIM_3) :: VR_XSI
  
    CALL COMPUTE_L_R_STATES_XSI(V, VL_XSI, VR_XSI)
  END SUBROUTINE C_COMPUTE_L_R_STATES_XSI
  

  
  SUBROUTINE C_COMPUTE_LIMITER_ETA(V_DIM_1, V_DIM_2, V_DIM_3, V, PSI_P_ETA_DIM_1, PSI_P_ETA_DIM_2, PSI_P_ETA_DIM_3, PSI_P_ETA, PSI_&
&M_ETA_DIM_1, PSI_M_ETA_DIM_2, PSI_M_ETA_DIM_3, PSI_M_ETA) BIND(C)
    USE ISO_C_BINDING, ONLY: C_BOOL
    USE FLUX_MODULE, ONLY: COMPUTE_LIMITER_ETA
    IMPLICIT NONE
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: V_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: V_DIM_2
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: V_DIM_3
    REAL(KIND=DP), INTENT(IN), DIMENSION(V_DIM_1,V_DIM_2,V_DIM_3) :: V
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: PSI_P_ETA_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: PSI_P_ETA_DIM_2
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: PSI_P_ETA_DIM_3
    REAL(KIND=DP), INTENT(OUT), DIMENSION(PSI_P_ETA_DIM_1,PSI_P_ETA_DIM_2,PSI_P_ETA_DIM_3) :: PSI_P_ETA
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: PSI_M_ETA_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: PSI_M_ETA_DIM_2
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: PSI_M_ETA_DIM_3
    REAL(KIND=DP), INTENT(OUT), DIMENSION(PSI_M_ETA_DIM_1,PSI_M_ETA_DIM_2,PSI_M_ETA_DIM_3) :: PSI_M_ETA
  
    CALL COMPUTE_LIMITER_ETA(V, PSI_P_ETA, PSI_M_ETA)
  END SUBROUTINE C_COMPUTE_LIMITER_ETA
  

  
  SUBROUTINE C_COMPUTE_L_R_STATES_ETA(V_DIM_1, V_DIM_2, V_DIM_3, V, VL_ETA_DIM_1, VL_ETA_DIM_2, VL_ETA_DIM_3, VL_ETA, VR_ETA_DIM_1,&
& VR_ETA_DIM_2, VR_ETA_DIM_3, VR_ETA) BIND(C)
    USE ISO_C_BINDING, ONLY: C_BOOL
    USE FLUX_MODULE, ONLY: COMPUTE_L_R_STATES_ETA
    IMPLICIT NONE
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: V_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: V_DIM_2
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: V_DIM_3
    REAL(KIND=DP), INTENT(IN), DIMENSION(V_DIM_1,V_DIM_2,V_DIM_3) :: V
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: VL_ETA_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: VL_ETA_DIM_2
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: VL_ETA_DIM_3
    REAL(KIND=DP), INTENT(OUT), DIMENSION(VL_ETA_DIM_1,VL_ETA_DIM_2,VL_ETA_DIM_3) :: VL_ETA
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: VR_ETA_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: VR_ETA_DIM_2
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: VR_ETA_DIM_3
    REAL(KIND=DP), INTENT(OUT), DIMENSION(VR_ETA_DIM_1,VR_ETA_DIM_2,VR_ETA_DIM_3) :: VR_ETA
  
    CALL COMPUTE_L_R_STATES_ETA(V, VL_ETA, VR_ETA)
  END SUBROUTINE C_COMPUTE_L_R_STATES_ETA
  

  
  SUBROUTINE C_VANLEER_FLUX(VLEFT_DIM_1, VLEFT, VRIGHT_DIM_1, VRIGHT, NX, NY, F_DIM_1, F) BIND(C)
    USE ISO_C_BINDING, ONLY: C_BOOL
    USE FLUX_MODULE, ONLY: VANLEER_FLUX
    IMPLICIT NONE
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: VLEFT_DIM_1
    REAL(KIND=DP), INTENT(IN), DIMENSION(VLEFT_DIM_1) :: VLEFT
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: VRIGHT_DIM_1
    REAL(KIND=DP), INTENT(IN), DIMENSION(VRIGHT_DIM_1) :: VRIGHT
    REAL(KIND=DP), INTENT(IN) :: NX
    REAL(KIND=DP), INTENT(IN) :: NY
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: F_DIM_1
    REAL(KIND=DP), INTENT(OUT), DIMENSION(F_DIM_1) :: F
  
    CALL VANLEER_FLUX(VLEFT, VRIGHT, NX, NY, F)
  END SUBROUTINE C_VANLEER_FLUX
  

  
  SUBROUTINE C_ROE_FLUX(VLEFT_DIM_1, VLEFT, VRIGHT_DIM_1, VRIGHT, NX, NY, F_DIM_1, F) BIND(C)
    USE ISO_C_BINDING, ONLY: C_BOOL
    USE FLUX_MODULE, ONLY: ROE_FLUX
    IMPLICIT NONE
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: VLEFT_DIM_1
    REAL(KIND=DP), INTENT(IN), DIMENSION(VLEFT_DIM_1) :: VLEFT
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: VRIGHT_DIM_1
    REAL(KIND=DP), INTENT(IN), DIMENSION(VRIGHT_DIM_1) :: VRIGHT
    REAL(KIND=DP), INTENT(IN) :: NX
    REAL(KIND=DP), INTENT(IN) :: NY
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: F_DIM_1
    REAL(KIND=DP), INTENT(OUT), DIMENSION(F_DIM_1) :: F
  
    CALL ROE_FLUX(VLEFT, VRIGHT, NX, NY, F)
  END SUBROUTINE C_ROE_FLUX
  

  
  SUBROUTINE C_COMPUTE_FLUX_XSI(VANLEER, V_DIM_1, V_DIM_2, V_DIM_3, V, NHAT_XSI_DIM_1, NHAT_XSI_DIM_2, NHAT_XSI_DIM_3, NHAT_XSI, F_&
&XSI_DIM_1, F_XSI_DIM_2, F_XSI_DIM_3, F_XSI) BIND(C)
    USE ISO_C_BINDING, ONLY: C_BOOL
    USE FLUX_MODULE, ONLY: COMPUTE_FLUX_XSI
    IMPLICIT NONE
    LOGICAL, INTENT(IN) :: VANLEER
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: V_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: V_DIM_2
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: V_DIM_3
    REAL(KIND=DP), INTENT(IN), DIMENSION(V_DIM_1,V_DIM_2,V_DIM_3) :: V
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: NHAT_XSI_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: NHAT_XSI_DIM_2
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: NHAT_XSI_DIM_3
    REAL(KIND=DP), INTENT(IN), DIMENSION(NHAT_XSI_DIM_1,NHAT_XSI_DIM_2,NHAT_XSI_DIM_3) :: NHAT_XSI
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: F_XSI_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: F_XSI_DIM_2
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: F_XSI_DIM_3
    REAL(KIND=DP), INTENT(OUT), DIMENSION(F_XSI_DIM_1,F_XSI_DIM_2,F_XSI_DIM_3) :: F_XSI
  
    CALL COMPUTE_FLUX_XSI(VANLEER, V, NHAT_XSI, F_XSI)
  END SUBROUTINE C_COMPUTE_FLUX_XSI
  

  
  SUBROUTINE C_COMPUTE_FLUX_ETA(VANLEER, V_DIM_1, V_DIM_2, V_DIM_3, V, NHAT_ETA_DIM_1, NHAT_ETA_DIM_2, NHAT_ETA_DIM_3, NHAT_ETA, F_&
&ETA_DIM_1, F_ETA_DIM_2, F_ETA_DIM_3, F_ETA) BIND(C)
    USE ISO_C_BINDING, ONLY: C_BOOL
    USE FLUX_MODULE, ONLY: COMPUTE_FLUX_ETA
    IMPLICIT NONE
    LOGICAL, INTENT(IN) :: VANLEER
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: V_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: V_DIM_2
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: V_DIM_3
    REAL(KIND=DP), INTENT(IN), DIMENSION(V_DIM_1,V_DIM_2,V_DIM_3) :: V
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: NHAT_ETA_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: NHAT_ETA_DIM_2
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: NHAT_ETA_DIM_3
    REAL(KIND=DP), INTENT(IN), DIMENSION(NHAT_ETA_DIM_1,NHAT_ETA_DIM_2,NHAT_ETA_DIM_3) :: NHAT_ETA
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: F_ETA_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: F_ETA_DIM_2
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: F_ETA_DIM_3
    REAL(KIND=DP), INTENT(OUT), DIMENSION(F_ETA_DIM_1,F_ETA_DIM_2,F_ETA_DIM_3) :: F_ETA
  
    CALL COMPUTE_FLUX_ETA(VANLEER, V, NHAT_ETA, F_ETA)
  END SUBROUTINE C_COMPUTE_FLUX_ETA
  
END MODULE C_FLUX_MODULE

