! This automatically generated Fortran wrapper file allows codes
! written in Fortran to be called directly from C and translates all
! C-style arguments into expected Fortran-style arguments (with
! assumed size, local type declarations, etc.).


MODULE C_UPWIND_MODULE
  IMPLICIT NONE


CONTAINS


  
  SUBROUTINE C_VANLEER_FLUX(VLEFT_DIM_1, VLEFT, VRIGHT_DIM_1, VRIGHT, NX, NY, F_DIM_1, F) BIND(C)
    USE ISO_C_BINDING, ONLY: C_BOOL
    USE UPWIND_MODULE, ONLY: VANLEER_FLUX
    IMPLICIT NONE
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: VLEFT_DIM_1
    REAL(KIND=8), INTENT(IN), DIMENSION(VLEFT_DIM_1) :: VLEFT
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: VRIGHT_DIM_1
    REAL(KIND=8), INTENT(IN), DIMENSION(VRIGHT_DIM_1) :: VRIGHT
    REAL(KIND=8), INTENT(IN) :: NX
    REAL(KIND=8), INTENT(IN) :: NY
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: F_DIM_1
    REAL(KIND=8), INTENT(OUT), DIMENSION(F_DIM_1) :: F
  
    CALL VANLEER_FLUX(VLEFT, VRIGHT, NX, NY, F)
  END SUBROUTINE C_VANLEER_FLUX
  

  
  SUBROUTINE C_ROE_FLUX(VLEFT_DIM_1, VLEFT, VRIGHT_DIM_1, VRIGHT, NX, NY, F_DIM_1, F) BIND(C)
    USE ISO_C_BINDING, ONLY: C_BOOL
    USE UPWIND_MODULE, ONLY: ROE_FLUX
    IMPLICIT NONE
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: VLEFT_DIM_1
    REAL(KIND=8), INTENT(IN), DIMENSION(VLEFT_DIM_1) :: VLEFT
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: VRIGHT_DIM_1
    REAL(KIND=8), INTENT(IN), DIMENSION(VRIGHT_DIM_1) :: VRIGHT
    REAL(KIND=8), INTENT(IN) :: NX
    REAL(KIND=8), INTENT(IN) :: NY
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: F_DIM_1
    REAL(KIND=8), INTENT(OUT), DIMENSION(F_DIM_1) :: F
  
    CALL ROE_FLUX(VLEFT, VRIGHT, NX, NY, F)
  END SUBROUTINE C_ROE_FLUX
  

  
  SUBROUTINE C_COMPUTE_L_R_STATES_ETA(V_DIM_1, V_DIM_2, V_DIM_3, V, IMAX, JMAX, VL_ETA_DIM_1, VL_ETA_DIM_2, VL_ETA_DIM_3, VL_ETA, V&
&R_ETA_DIM_1, VR_ETA_DIM_2, VR_ETA_DIM_3, VR_ETA) BIND(C)
    USE ISO_C_BINDING
    USE ISO_C_BINDING, ONLY: C_BOOL
    USE UPWIND_MODULE, ONLY: COMPUTE_L_R_STATES_ETA
    IMPLICIT NONE
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: V_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: V_DIM_2
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: V_DIM_3
    REAL(KIND=8), INTENT(IN), DIMENSION(V_DIM_1,V_DIM_2,V_DIM_3) :: V
    INTEGER(KIND=C_INT), INTENT(IN) :: IMAX
    INTEGER(KIND=C_INT), INTENT(IN) :: JMAX
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: VL_ETA_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: VL_ETA_DIM_2
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: VL_ETA_DIM_3
    REAL(KIND=8), INTENT(OUT), DIMENSION(VL_ETA_DIM_1,VL_ETA_DIM_2,VL_ETA_DIM_3) :: VL_ETA
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: VR_ETA_DIM_1
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: VR_ETA_DIM_2
    INTEGER(KIND=SELECTED_INT_KIND(18)), INTENT(IN) :: VR_ETA_DIM_3
    REAL(KIND=8), INTENT(OUT), DIMENSION(VR_ETA_DIM_1,VR_ETA_DIM_2,VR_ETA_DIM_3) :: VR_ETA
  
    CALL COMPUTE_L_R_STATES_ETA(V, IMAX, JMAX, VL_ETA, VR_ETA)
  END SUBROUTINE C_COMPUTE_L_R_STATES_ETA
  
END MODULE C_UPWIND_MODULE

